### ISSUE TITLE
Add more information about the region

### ISSUE THREAD

**Issue by coder66** [devasworski/Corona-Info#15]
Instead of showing a city name, please be more precise and show the actual area the data is for. In the attached screenshot it should be "Kreis Freising" and not the city Feising. Interpreting the data can be misleading this way.

![Screenshot_20200420_082157_com corona_info](https://user-images.githubusercontent.com/14278231/79756352-cb372a80-831a-11ea-9d91-c05b02e766bc.jpg)

**Comment by devasworski** [comment]
The name of the area comes from the API and will be determined by the API over your GPS coordinates. The app has no influence on the name of the area. Therefore, you are seeing the data for "Freising" and not "Landkreis Freising", because according to your GPS the API determines, that you are in "Freising".

**Comment by coder66** [comment]
Yes, but the data is not for the city of Freising, which the name would imply. Therefor it is misleading.

**Comment by devasworski** [comment]
This is then a issue with the source the NPGEO-DE. 
I am using official unchanged data from a [governmental source.](https://npgeo-corona-npgeo-de.hub.arcgis.com/)

**Comment by coder66** [comment]
Then just add a header above Freising to say:

"Region"

**Comment by devasworski** [comment]
I am sorry, but this would defeat the purpose showing the data unchanged
